let seed = 7143624
let bid = "normal"

let bg_colors = {
    0.0: [15,15,15],
    12.0: [25,25,25],
    24.0: [15,15,15]
}
let mid = ['"Tätä ei oo koskaan tapahtunu aikasemmin"', "Voiko edes puhua speedrun-maratonista jos tätä ei kuulu?"]

let choises = [
    ["Lahjoita MIELI ry:lle!", "Lahjoita rahaa hyväntekeväisyyteen Vauhtijuoksun nettisivujen kautta."],
["Chatti bäckseattaa", "Chatti kertoo asiantuntijana, miten jokin asia pitäisi tehdä."],
["Uusi Oma Ennätys", "Pelaaja saa uuden personal bestin eli PB:n eli oman ennätyksen!"],
["Toistuva voiceline pelissä", "Esim. jokin pelin NPC:stä toistaa samaa puheenpätkää useaan otteeseen."],
["Yleisö vilkuttaa kameralle", "Bongaa vilkuttaja yleisöstä."],
["Koe out of bounds -elämys", "Pelissä mennään pelialueen ulkopuolelle, jonne ei kuuluisi päästä."],
["Postaa Vauhtis-tunnelmakuva someen", "Ota kuva omasta Vauhtis-katsomosta ja postaa se sosiaaliseen mediaan."],
["Katso kokonainen runi", "Katso pelisuoritus alusta loppuun."],
["Chattaile 03:00 - 06:00", "Viestittele chattiin aamuyön tunteina."],
["Bongaa Vauhtijuoksu-paita", "Pelaajalla, Toimitsijalla tai yleisöllä on Vauhtijuoksu-paita päällään."],
["Teknisiä ongelmia", "Tekniikka pettää, esim. pelaajan ohjain tökkii tai videokuva jäätyy."],
["F", "Pelaaja kuolee pelissä tai jotain muuta traagista tapahtuu. Press F to pay respect."],
["Opi uutta tutusta pelistä", "Speedrun voi opettaa jotain uutta ennaltaan tutusta pelistä."],
["Kaksi pelaajaa yhteistyössä", "Katso co-op runi, jossa 2+ pelaajaa pelaa yhteisen tavoitteen puolesta."],
["Erittäin hyvä RNG", "Pelaajalla käy erittäin hyvä tuuri jonkin asian suhteen."],
["Erittäin huono RNG", "Pelaajalla käy erittäin huono tuuri jonkin asian suhteen."],
["Yli 100€ lahjoitus!", "Joku lahjoittaa yli 100€ MIELI ry:lle!"],
["Unskippable cutscene", "Pelissä tulee videonpätkä, jota ei yksinkertaisesti pysty skippaamaan."],
["Pelaajat kisaavat keskenään", "Katso race, jossa 2+ pelaajaa kilpailee keskenään siitä, kuka on nopein."],
["Vauhtisbiisi", 'Striimissä soitetaan Vauhtisbiisiä eli "Deerboy - Medley No.1 (Vauhtijuoksu Edit)".'],
["Näe resetti", "Pelaajalla mokaa ja joutuu sen vuoksi aloittamaan suorituksen alusta."],
["Joku syö striimissä", "Pelaaja tai Toimitsija on eksynyt keittiöstä striimin puolelle syömään."],
["Hauska lahjoitusviesti", "Joku heittää mieletöntä läppää lahjoitusviestin muodossa."],
["vauhtiJAM-moment", "Striimin musiikit saa chatin suoltamaan vauhtiJAM-emotea."],
["Äitille terkkuja", "Joku lähettää terveiset äidille."],
["“Ekalla!“", "Pelaaja pääsee skipin ensimmäisellä yrityksellä."],
["Framen tarkka temppu", "Frame perfect eli tempun aikaikkuna on vain yhden ruudunpäivityksen mittainen."],
["Terveiset kotopuolesta", "Pelaajan kotiväki lähettää terveiset pelaajalle lahjoitusviestin muodossa."],
["Chatti keittää pastaa", "Joku on keksinyt hyvän copy-pasten, joka leviää chatissa."],
["Viuhtikas vilahdus", "Maskotti Viuhti vilahtaa ruudussa."],
["Kruisaillaan", "Katso runi, jossa ajellaan."],
["Hei, me lennetään!", "Katso runi, jossa lennetään tai liidetään."],
["Tavoite saavutettu", "Ole paikalla, kun lahjoitustavoite täyttyy."],
["Antiikkia, antiikkia", "Katso peliä, joka on tehty viime vuosituhannella."],
["Bongaa energiajuoma", "Pelaaja, Toimitsija tai yleisön edustaja nauttii vauhdikasta juomaa."],
["Ja seuraavaksi mainoksia", "Katso kaupalliset tiedotteet."],
["Bossi ei kiinnosta", "Päävihu kuolee sekunneissa tai se ohitetaan kokonaan."],
["Moogle ruudussa", "Bongaa Final Fantasyistä tuttu pallonaama pelissä."],
["Heppatyttöpeli", "Pelissä heppaillaan, taikatyttöillään tai muuten ollaan maagisia heppatyttöjä."],
["Pokémon palloon!", "Todista, kun pelissä napataan taskumonsteri."],
["Hevimeininkiä", "Teeman mukaista raskasta tunnelmaa."],
["Game Over!", "Joku häviää pelin, kuolee tai ottaa muuten pataan kesken runin."],
["Peli rikotaan tahallaan", "Pelissä mennään seinien läpi, syötetään koodia tai muuten säretään jotain runia varten."],
["It's over 100%", "Runin kategoriassa on prosenttiluku, joka on yli 100% "],
["Arts and crafts", "Bongaa, kun joku tekee käsitöitä yleisössä."],
["Tunnen runnaajan IRL", "Pystyt käyttämän runnaajan etunimeä, koska tunnette oikeassa elämässä."],
["Bongaa mini-Viuhti", "Näe striimissä Viuhtin miniversio tai sen synnyinprosessi!"],
["Ai noin se tehdään", "Pelaaja vetää pelistä kohdan jota et ole itse päässyt läpi"],
["Täytä palautekysely", "Käy antamassa palautetta Vauhtijuoksu 2025 -tapahtumasta!"],
["Corpse paint bongattu!", "Spottaa ihminen, jolle on tehty hevimeikki."],
["Mielinauha ruudussa", "Katso striimiä, kun esillä on ihka oikea Mielinauha."],
["Pelaaja silittää karvakaveria", "Pelissä pysähdytään silittämään eläintä."],
["En ymmärrä tätä kieltä", "Peliä pelataan jollain muulla kuin englannin tai suomen kielellä."],
["Muotinäytös!", "Pelaaja vaihtaa hahmon vaatteet."],
["Ninjatime", "Runissa hypitään seinille, sniikkaillaan tai muuten ninjotaan menemään."],
["Randomizer", "Runissa randomoidaan eli satunnaistetaan jokin osa!"],
["Seikkaillaan epäihmisenä", "Pelin päähenkilö on joku muu kuin ihminen."],
["Järjestellään palikoita", "Tavoitteena pelissä saaha Tetris, Puyo Puyo tai joku muu palikkarivi järjestykseen."],
["Pumppu pettää", "Katso runi, jossa pelaajalla on sykevyö."],
["Bonusohjelmaa!", "Ole paikalla, kun ruudussa on bonusohjelmaa."],
["*Nappien hakkaamista*", "Pelaajan ohjaimen/näppäimistön hakkaaminen kuuluu striimiin asti."],
["Sohvalla on tilaa", "Katso runi, jolla on enemmän kuin 2 kommentaattoria."],
["Counteri ruudulla", "Näe runi, jossa pelaaja pitää kirjaa esim. kuolemista tai kirosanoista."],
["Cosplay-tunnelmaa", "Runnaaja tai sohva ilmestyy paikalle pelistä inspiroituneessa asussa."],
["“Oho“", "Jotain odottamatonta tapahtuu ja pelaaja reagoi asianmukaisesti."],
]