let seed = 4343424
let bid = "kalas"

let bg_colors = {
    0.0: [52,95,101],
    12.0: [92,187,114],
    24.0: [52,95,101]
}
let mid = [
  "CREATURE.gif",
  "Anomalocaris.webp",
  "Helicoprion.webp",
  "Horseshoe_Crab.webp",
  "Leedsichthys.webp",
  "Golden_Bass.webp",
  "Golden_Manta_Ray.webp",
]

let choises = [
    "Alligator.webp",
    "Angelfish.webp",
    "Atlantic_Salmon.webp",
    "Axolotl.webp",
    "Bluefish.webp",
    "Bluegill.webp",
    "Bone.webp",
    "Bowfin.webp",
    "Branch.webp",
    "Bull_Shark.png",
    "Carp.webp",
    "Catfish.webp",
    "Clownfish.webp",
    "Coelacanth.webp",
    "Crab.webp",
    "Crappie.webp",
    "Crayfish.webp",
    "Diamond.webp",
    "Dogfish.webp",
    "Drink_Rings.webp",
    "Drum.webp",
    "Eel.webp",
    "Flounder.webp",
    "Frog.webp",
    "Gar.webp",
    "Goldfish.webp",
    "Great_White_Shark.webp",
    "Grouper.webp",
    "Guppy.webp",
    "Hammerhead_Shark.webp",
    "Herring.webp",
    "King_Salmon.webp",
    "Koi.webp",
    "Krill.webp",
    "Largemouth_Bass.webp",
    "Leech.webp",
    "Lionfish.webp",
    "Lobster.webp",
    "Man_O_War.webp",
    "Manta_Ray.webp",
    "Marlin.webp",
    "Mooneye.webp",
    "Muskellunge.webp",
    "Octopus.webp",
    "Old_Boot.webp",
    "Oyster.webp",
    "Perch.webp",
    "Pike.webp",
    "Plastic_Bag.webp",
    "Pupfish.webp",
    "Rainbow_Trout.webp",
    "Salmon.webp",
    "Sawfish.webp",
    "Sea_Turtle.webp",
    "Seahorse.webp",
    "Shrimp.webp",
    "Snail.webp",
    "Soda_Can.webp",
    "Squid.webp",
    "Sting_Ray.webp",
    "Sturgeon.webp",
    "Sunfish.webp",
    "Swordfish.webp",
    "Toad.webp",
    "Tuna.png",
    "Turtle.webp",
    "Walleye.webp",
    "Weed.webp",
    "Whale.webp",
    "Wolffish.webp",
    "Unidentified_Fish_Object.webp",
]

